### PR TITLE
Fix missing AES util

### PR DESCRIPTION
**Pull request by tillkruss**
When installing this the `dist/util` folder is missing.

### CODE REVIEW

**Comment by junicello** [comment]
@mroth When can we expect the fix to be merged?

**Comment by mroth** [comment]
Hi, I'm not sure what this would do? -- in my fork (which I had started working on the `develop` branch, but haven't had time to invest in lately) I completely removed that file, see https://github.com/mroth/homebridge-airmega/commit/23f48ae5a5c9eb5353a2bc2591153cc1d4436fa5.

**Comment by junicello** [comment]
Since upgrading homebrdige to 1.3.5, the following error shows up when restarting.

[10/28/2021, 17:27:53] ====================
[10/28/2021, 17:27:53] ERROR LOADING PLUGIN @mroth/homebridge-airmega:
[10/28/2021, 17:27:53] Error: Cannot find module './util/aes'
Require stack:
- ***@***.***/homebridge-airmega/dist/lib/Authenticator.js
- ***@***.***/homebridge-airmega/dist/lib/AirmegaPlatform.js
- ***@***.***/homebridge-airmega/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> ***@***.***/homebridge-airmega/lib/Authenticator.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> ***@***.***/homebridge-airmega/lib/AirmegaPlatform.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> ***@***.***/homebridge-airmega/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:187:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:126:16
    at Map.forEach (<anonymous>)
[10/28/2021, 17:27:53] ====================
[10/28/2021, 17:27:53] Loading 2 platforms...
[10/28/2021, 17:27:53] [Config] Initializing config platform...
[10/28/2021, 17:27:53] [Config] Running in Service Mode
[10/28/2021, 17:27:53] No plugin was found for the platform "Airmega" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by camberos** [comment]
It would be great if you can merge this fix.

**Comment by zzysunny** [comment]
Any update on merging this?

**Comment by hendrik42** [comment]
Same error message for me
